---
- hosts: all
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
    ansible_port: 5986
  tasks:

  - name: Install NFS Client
    ansible.windows.win_feature:
      name: NFS-Client
      state: present
